name: secure-coding
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - flask==2.0.1
    - flask-socketio==5.1.1
    - flask-cors==3.0.10
    - flask-wtf==0.15.1
    - python-dotenv==0.19.0
    - werkzeug==2.0.1
    - markupsafe==2.0.1
    - eventlet==0.33.0
    - python-engineio==4.3.0
    - python-socketio==5.5.0
    - sqlalchemy==1.4.23
    - requests==2.26.0
    - uuid==1.30 